# Generated by Django 3.2.5 on 2021-12-17 01:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0002_alter_currency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='trx_ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
