# Generated by Django 3.2.5 on 2021-12-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0003_auto_20211217_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='trx_ref',
            new_name='tx_ref',
        ),
        migrations.AddField(
            model_name='payment',
            name='redirect_url',
            field=models.CharField(default='https://webhook.site/9d0b00ba-9a69-44fa-a43d-a82c33c36fdc', max_length=100),
        ),
    ]
