# Generated by Django 3.2.5 on 2021-12-17 02:36

from django.db import migrations, models
import premium.models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_auto_20211217_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(default=premium.models.paymentId, max_length=256),
        ),
    ]
